import './globals.css'
import { Inter , Roboto , Poppins } from 'next/font/google'
import Navbar from '@/Components/navbar/navbar'
import Footer from '@/Components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CyberGuard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className='container'>
      <Navbar />
      {children}
      <Footer/>
      </div>
      </body>
    </html>
  )
}
